### PR TITLE
Set the class in componetns user

### PR DESCRIPTION
**Pull request by milorojas**
if u dont set the class for the componet user u get the next error `Calling unknown method: yii\web\User::getFlashes()`

### CODE REVIEW

**Comment by soltmar** [comment]
User component is automatically set through Bootstrap class.
You need to make sure that you don't have user component class configured in web.php config file.

Please can you give some more details about error? 
your web.php config file and when are you see this error ?

Thanks

**Comment by milorojas** [comment]
This is my user components (With that line comment) i am getting this error `Calling unknown method: yii\web\User::getFlashes()`

`'components' => [`
      `'user' => [`
          `'identityClass' => 'marsoltys\yii2user\models\User',`
          `//'class' => 'marsoltys\yii2user\components\User',`
          `'enableAutoLogin' => true,`
   `],`
  `],``

And this is my user module
`'user' => [`
           `'class' => 'marsoltys\yii2user\Module',`
            `'userClass' => 'marsoltys\yii2user\components\User',` 
            `'identityClass' => 'marsoltys\yii2user\models\User',`
           `'userModel' => 'marsoltys\yii2user\models\`
`],`

i check the bootstrap and you are right but if i uncomment this line `//'class' => 'marsoltys\yii2user\components\User',` works totally fine. 

Thanks for ur help.

**Comment by milorojas** [comment]
nevermind it was my `'bootstrap' => ['log'],` in my web.php

`'bootstrap' => ['log','marsoltys\yii2user\Bootstrap'],`

Thanks

**Comment by soltmar** [comment]
You shouldn't even add this to bootstrap section. This should be done by setting in composer.json

`"extra": {
        "bootstrap": "marsoltys\\yii2user\\Bootstrap"
    },`

**Comment by milorojas** [comment]
Thanks, i will put that on the composer.json and delete that for my `'bootstrap' => [ .....]`

**Pull request closed without merging**
